// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KFM.Data.Models;

public partial class FoodRequirement
{
    public int FoodId { get; set; }

    public int? KoiId { get; set; }

    public string DevelopmentStage { get; set; }

    public double? RequiredAmount { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual KoiFish Koi { get; set; }
}