// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KFM.Data.Models;

public partial class KoiFish
{
    public int KoiId { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public string BodyShape { get; set; }

    public int? Age { get; set; }

    public double? Size { get; set; }

    public double? Weight { get; set; }

    public string Gender { get; set; }

    public string Breed { get; set; }

    public string Origin { get; set; }

    public decimal? Price { get; set; }

    public int? PondId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<FoodRequirement> FoodRequirements { get; set; } = new List<FoodRequirement>();

    public virtual ICollection<KoiGrowth> KoiGrowths { get; set; } = new List<KoiGrowth>();

    public virtual Pond Pond { get; set; }
}