// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KFM.Data.Models;

public partial class SaltRequirement
{
    public int SaltId { get; set; }

    public int? PondId { get; set; }

    public double? RequiredSaltAmount { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Pond Pond { get; set; }
}