// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KFM.Data.Models;

public partial class WaterParameter
{
    public int ParameterId { get; set; }

    public int? PondId { get; set; }

    public DateOnly? DateMeasured { get; set; }

    public double? Temperature { get; set; }

    public double? SaltLevel { get; set; }

    public double? Phlevel { get; set; }

    public double? O2level { get; set; }

    public double? No2level { get; set; }

    public double? No3level { get; set; }

    public double? Po4level { get; set; }

    public string Recommendation { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Pond Pond { get; set; }
}